server:
  port: 9010
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/socialmedia
    username: root
    password: pass@word1

  jpa:
    hibernate:
      ddl-auto: update
      ssl-auto: true